//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLI_GA_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public long RatingId { get; set; }
        public int UserId { get; set; }
        public int MovieId { get; set; }
        public double Rate { get; set; }
    
        public virtual Movie Movy { get; set; }
    }
}
