//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLI_GA_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Ratings = new List<Rating>();
        }
    
        public int UserId { get; set; }
        public Nullable<double> Age { get; set; }
        public bool Sex { get; set; }
        public int OccupationId { get; set; }

        public double SimilarityWithActiveUser { get; set; } = 0;
        public double PearsonValue { get; set; } = 0;

        public virtual Occupation Occupation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Rating> Ratings { get; set; }
    }
}
